sync_prod:
  js:
    js/sync_prod.js: {}
  dependencies:
    - core/jquery
    - core/jquery.once
    
test_prod:
  css:
    theme:
      css/test_prod.css: {}
  js:
    js/test_prod.js: {}
  dependencies:
    - core/jquery
